export enum MODAL_TYPES {
  MAKE_RESERVATION_MODAL = 'MAKE_RESERVATION_MODAL',
  CONFIRMATION_MODAL = 'CONFIRMATION_MODAL',
  ADD_ADDRESS_MODAL = 'ADD_ADDRESS_MODAL',
  EDIT_ADDRESS_MODAL = 'EDIT_ADDRESS_MODAL',
}
