//libs
import Head from 'next/head';
import {motion} from 'framer-motion';

//components
import {Box, Breadcrumb, BreadcrumbItem, BreadcrumbLink, Stack} from '@chakra-ui/react';
import {BlogCard} from '@/components/blogCard';

//constants
import {BLOGS} from '@/modules/homePage/constants';

const ANIMATION_VARIANTS = {
  initial: {opacity: 0, y: 20},
  animate: {opacity: 1, y: 0},
  exit: {opacity: 0, y: 0},
};

export default function BlogsPage() {
  return (
    <>
      <Head>
        <title>Stories</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box as="main">
        <Box
          height={'400px'}
          backgroundPosition="center"
          backgroundRepeat="no-repeat"
          backgroundSize="cover"
          backgroundImage="https://preview.colorlib.com/theme/feliciano/images/bg_1.jpg.webp"
          backgroundAttachment="fixed"
          width="full"
          display="flex"
          alignItems="center"
        >
          <Stack
            spacing={0}
            direction="column"
            alignItems="center"
            justifyContent="flex-end"
            height="full"
            width="full"
            backgroundColor="blackAlpha.700"
            pb={8}
          >
            <Box fontSize="4xl" fontWeight="extrabold" color="white">
              Blogs
            </Box>

            <Breadcrumb fontSize="xs" color="white" textTransform="uppercase">
              <BreadcrumbItem>
                <BreadcrumbLink href="/">Home</BreadcrumbLink>
              </BreadcrumbItem>

              <BreadcrumbItem>
                <BreadcrumbLink href="/stories">Blogs</BreadcrumbLink>
              </BreadcrumbItem>
            </Breadcrumb>
          </Stack>
        </Box>

        <Box py={16} px={4} maxWidth={1100} mx="auto">
          <motion.div
            initial="initial"
            animate="animate"
            variants={ANIMATION_VARIANTS}
            transition={{duration: 0.2}}
          >
            <Box display="grid" gridTemplateColumns={{md: 'repeat(3, 1fr)', sm: '1fr'}} gap={4}>
              {[...BLOGS, ...BLOGS].map((blog) => (
                <BlogCard key={blog.id} blog={blog} />
              ))}
            </Box>
          </motion.div>
        </Box>
      </Box>
    </>
  );
}
