//libs
import Head from 'next/head';
import {motion} from 'framer-motion';

//components
import {Box, Breadcrumb, BreadcrumbItem, BreadcrumbLink, Stack} from '@chakra-ui/react';
import {ContactUsForm} from '@/components/contactUsForm';

const ANIMATION_VARIANTS = {
  initial: {opacity: 0, y: 20},
  animate: {opacity: 1, y: 0},
  exit: {opacity: 0, y: 0},
};

export default function BlogsPage() {
  return (
    <>
      <Head>
        <title>Contact Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box as="main">
        <Box
          height={'400px'}
          backgroundPosition="center"
          backgroundRepeat="no-repeat"
          backgroundSize="cover"
          backgroundImage="https://preview.colorlib.com/theme/feliciano/images/bg_3.jpg.webp"
          backgroundAttachment="fixed"
          width="full"
          display="flex"
          alignItems="center"
        >
          <Stack
            spacing={0}
            direction="column"
            alignItems="center"
            justifyContent="flex-end"
            height="full"
            width="full"
            backgroundColor="blackAlpha.700"
            pb={8}
          >
            <Box fontSize="4xl" fontWeight="extrabold" color="white">
              Contact Us
            </Box>

            <Breadcrumb fontSize="xs" color="white" textTransform="uppercase">
              <BreadcrumbItem>
                <BreadcrumbLink href="/">Home</BreadcrumbLink>
              </BreadcrumbItem>

              <BreadcrumbItem>
                <BreadcrumbLink href="/contact">Contact Us</BreadcrumbLink>
              </BreadcrumbItem>
            </Breadcrumb>
          </Stack>
        </Box>

        <Box py={16} px={4} maxWidth={1100} mx="auto">
          <motion.div
            initial="initial"
            animate="animate"
            variants={ANIMATION_VARIANTS}
            transition={{duration: 0.2}}
          >
            <Box display="flex" gap={8} flexDirection={{md: 'row', sm: 'column'}}>
              <Box
                flex={1}
                borderWidth={1}
                borderStyle="solid"
                borderColor="blackAlpha.400"
                alignSelf={{md: 'flex-start'}}
              >
                <iframe
                  src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3506.452221108747!2d77.08609031035704!3d28.49603899016599!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390d19387262e51d%3A0xc648fb515228d28c!2sImperfecto%20Cyberhub!5e0!3m2!1sen!2ssg!4v1685380265107!5m2!1sen!2ssg"
                  width="100%"
                  height="500px"
                  style={{
                    border: '0px',
                  }}
                  loading="lazy"
                  referrerPolicy="no-referrer-when-downgrade"
                ></iframe>
              </Box>

              <Box flex={1} height="700px">
                <ContactUsForm />
              </Box>
            </Box>

            <Box fontWeight="bold" fontSize="2xl" my={8}>
              Contact Information
            </Box>

            <Box display="flex" gap={8} flexDirection={{md: 'row', sm: 'column'}}>
              <Box flex={1}>
                Address:{' '}
                <Box as="span" color="brand.500">
                  198 West 21th Street, Suite 721 New York NY 10016
                </Box>
              </Box>

              <Box flex={1}>
                Phone:{' '}
                <Box as="span" color="brand.500">
                  +1235 2355 98
                </Box>
              </Box>

              <Box flex={1}>
                Email:{' '}
                <Box as="span" color="brand.500">
                  support@perfecto.com
                </Box>
              </Box>

              <Box flex={1}>
                Website:{' '}
                <Box as="span" color="brand.500">
                  perfecto.com
                </Box>
              </Box>
            </Box>
          </motion.div>
        </Box>
      </Box>
    </>
  );
}
