//libs
import Head from 'next/head';

//components
import {Box} from '@chakra-ui/react';
import {Carousel} from '@/components/carousel';

//constants
import {HOME_PAGE_CAROUSEL_CARDS} from '@/modules/homePage/constants';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box as="main" height="100vh">
        <Carousel cards={HOME_PAGE_CAROUSEL_CARDS} />
      </Box>
    </>
  );
}
