//libs
import Head from 'next/head';
import {motion} from 'framer-motion';

//components
import {Box} from '@chakra-ui/react';
import {CarouselSection} from '@/components/carouselSection';
import {AboutSection} from '@/modules/homePage/sections/AboutSection';
import {StatsSection} from '@/modules/homePage/sections/StatsSection';
import {SpecialtiesSection} from '@/modules/homePage/sections/SpecialtiesSection';
import {MakeReservationSection} from '@/modules/homePage/sections/MakeReservationSection';
import {RecentBlogPostsSection} from '@/modules/homePage/sections/RecentBlogPostsSection';

//constants
import {HOME_PAGE_CAROUSEL_CARDS, STATS} from '@/modules/homePage/constants';

const ANIMATION_VARIANTS = {
  initial: {opacity: 0, y: 20},
  animate: {opacity: 1, y: 0},
  exit: {opacity: 0, y: 0},
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box as="main">
        <CarouselSection cards={HOME_PAGE_CAROUSEL_CARDS} />

        <motion.div
          initial="initial"
          animate="animate"
          variants={ANIMATION_VARIANTS}
          transition={{duration: 0.2}}
        >
          <AboutSection />
        </motion.div>

        <StatsSection stats={STATS} />
        <SpecialtiesSection />
        <MakeReservationSection />
        <RecentBlogPostsSection />
      </Box>
    </>
  );
}
