//libs
import Head from 'next/head';

//components
import {
  Box,
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  Stack,
  Tab,
  TabList,
  TabPanel,
  TabPanels,
  Tabs,
} from '@chakra-ui/react';
import {ItemCard} from '@/components/itemCard';
import {motion, AnimatePresence} from 'framer-motion';

//constants
import {FOOD_ITEMS} from '@/modules/homePage/constants';

const ANIMATION_VARIANTS = {
  initial: {opacity: 0, y: 20},
  animate: {opacity: 1, y: 0},
  exit: {opacity: 0, y: 0},
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Menu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box as="main">
        <Box
          height={'400px'}
          backgroundPosition="center"
          backgroundRepeat="no-repeat"
          backgroundSize="cover"
          backgroundImage="https://preview.colorlib.com/theme/feliciano/images/bg_1.jpg.webp"
          backgroundAttachment="fixed"
          width="full"
          display="flex"
          alignItems="center"
        >
          <Stack
            spacing={0}
            direction="column"
            alignItems="center"
            justifyContent="flex-end"
            height="full"
            width="full"
            backgroundColor="blackAlpha.700"
            pb={8}
          >
            <Box fontSize="4xl" fontWeight="extrabold" color="white">
              Specialties
            </Box>

            <Breadcrumb fontSize="xs" color="white" textTransform="uppercase">
              <BreadcrumbItem>
                <BreadcrumbLink href="/">Home</BreadcrumbLink>
              </BreadcrumbItem>

              <BreadcrumbItem>
                <BreadcrumbLink href="/menu">Menu</BreadcrumbLink>
              </BreadcrumbItem>
            </Breadcrumb>
          </Stack>
        </Box>

        <Box py={20} px={4} maxWidth={1100} mx="auto">
          <Tabs isLazy variant="soft-rounded" colorScheme="brand" size={{sm: 'sm', md: 'md'}}>
            <TabList>
              <Tab>Breakfast</Tab>
              <Tab>Lunch</Tab>
              <Tab>Dinner</Tab>
              <Tab>Drinks</Tab>
              <Tab>Desserts</Tab>
              <Tab>Wine</Tab>
            </TabList>

            <AnimatePresence>
              <TabPanels py={8}>
                <TabPanel>
                  <motion.div
                    initial="initial"
                    animate="animate"
                    variants={ANIMATION_VARIANTS}
                    transition={{duration: 0.2}}
                  >
                    <Box
                      maxWidth={{md: '5xl', sm: 'full'}}
                      mx="auto"
                      display="grid"
                      gridTemplateColumns={{md: 'repeat(2, 1fr)', sm: '1fr'}}
                    >
                      {FOOD_ITEMS.map((foodItem) => (
                        <ItemCard key={foodItem.id} item={foodItem} />
                      ))}
                    </Box>
                  </motion.div>
                </TabPanel>
                <TabPanel>
                  <motion.div
                    initial="initial"
                    animate="animate"
                    variants={ANIMATION_VARIANTS}
                    transition={{duration: 0.2}}
                  >
                    <Box
                      maxWidth="5xl"
                      mx="auto"
                      display="grid"
                      gridTemplateColumns={{md: 'repeat(2, 1fr)', sm: '1fr'}}
                    >
                      {FOOD_ITEMS.map((foodItem) => (
                        <ItemCard key={foodItem.id} item={foodItem} />
                      ))}
                    </Box>
                  </motion.div>
                </TabPanel>
                <TabPanel>
                  <motion.div
                    initial="initial"
                    animate="animate"
                    variants={ANIMATION_VARIANTS}
                    transition={{duration: 0.2}}
                  >
                    <Box
                      maxWidth="5xl"
                      mx="auto"
                      display="grid"
                      gridTemplateColumns={{md: 'repeat(2, 1fr)', sm: '1fr'}}
                    >
                      {FOOD_ITEMS.map((foodItem) => (
                        <ItemCard key={foodItem.id} item={foodItem} />
                      ))}
                    </Box>
                  </motion.div>
                </TabPanel>
                <TabPanel>
                  <motion.div
                    initial="initial"
                    animate="animate"
                    variants={ANIMATION_VARIANTS}
                    transition={{duration: 0.2}}
                  >
                    <Box
                      maxWidth="5xl"
                      mx="auto"
                      display="grid"
                      gridTemplateColumns={{md: 'repeat(2, 1fr)', sm: '1fr'}}
                    >
                      {FOOD_ITEMS.map((foodItem) => (
                        <ItemCard key={foodItem.id} item={foodItem} />
                      ))}
                    </Box>
                  </motion.div>
                </TabPanel>
                <TabPanel>
                  <motion.div
                    initial="initial"
                    animate="animate"
                    variants={ANIMATION_VARIANTS}
                    transition={{duration: 0.2}}
                  >
                    <Box
                      maxWidth="5xl"
                      mx="auto"
                      display="grid"
                      gridTemplateColumns={{md: 'repeat(2, 1fr)', sm: '1fr'}}
                    >
                      {FOOD_ITEMS.map((foodItem) => (
                        <ItemCard key={foodItem.id} item={foodItem} />
                      ))}
                    </Box>
                  </motion.div>
                </TabPanel>
                <TabPanel>
                  <motion.div
                    initial="initial"
                    animate="animate"
                    variants={ANIMATION_VARIANTS}
                    transition={{duration: 0.2}}
                  >
                    <Box
                      maxWidth="5xl"
                      mx="auto"
                      display="grid"
                      gridTemplateColumns={{md: 'repeat(2, 1fr)', sm: '1fr'}}
                    >
                      {FOOD_ITEMS.map((foodItem) => (
                        <ItemCard key={foodItem.id} item={foodItem} />
                      ))}
                    </Box>
                  </motion.div>
                </TabPanel>
              </TabPanels>
            </AnimatePresence>
          </Tabs>
        </Box>
      </Box>
    </>
  );
}
